### ISSUE TITLE
Tried this deployement linux environment. encountering the following error stacktrace for signingCertificateFilesaused by: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'signingCertificateFiles' threw exception; nested exception is java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by pavankovela** [Unicon/cas-adfs-integration#15]

**Comment by pavankovela** [comment]
aused by: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'signingCertificateFiles' threw exception; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:101) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:57) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1450) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1158) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-3.2.6.RELEASE.jar:3.2.6.RELEASE]
        at org.springframework.beans.factory.suppor

**Comment by pavankovela** [comment]
when tried in windows its working fine wherever the .cer file is placed. but in the Linux environment though the cer path is given correctly . its throwing this error

**Comment by pavankovela** [comment]
wsfederation.xml

<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
       
    <description>
        This configures the WS-Federation support module.
    </description>
    
    <bean id="wsFederationAction" class="net.unicon.cas.support.wsfederation.web.flow.WsFederationAction">
       <property name="centralAuthenticationService" ref="centralAuthenticationService" />
        <property name="configuration" ref="wsFedConfig" />
    </bean>
    
    <bean id="wsFedConfig" class="net.unicon.cas.support.wsfederation.WsFederationConfiguration">
        
        <property name="identityProviderIdentifier" value="http://hydhtc353760d.ad.infosys.com/adfs/services/trust" />
        <property name="identityProviderUrl" value="https://hydhtc353760d.ad.infosys.com/adfs/ls" />
        <property name="identityAttribute" value="upn" />
        <property name="relyingPartyIdentifier" value="cas:mana:adfs" />
        <property name="tolerance" value="60000" />
       <property name="attributeMutator">
            <bean class="org.example.cas.support.wsfederation.WsFedAttributeMutatorImpl" />
        </property>
       <property name="signingCertificateFiles">
            <list>
                <value>file:/home/iipadmin/adfs.cer</value>
            </list>
        </property>
    </bean>
</beans>
